import Header from '@/components/header'
import Main from '@/components/main'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Mylo',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="es" className="bg-dark">
            <body
                className={`${inter.className} flex flex-col items-center text-light`}
            >
                <Header />
                <Main>{children}</Main>
            </body>
        </html>
    )
}
